force-app/main/default/objects/Object_A__c/Object_A__c.object-meta.xml
<CustomObject>
    <label>Object A</label>
    <nameField>
        <label>Object A Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objects A</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_B__c/Object_B__c.object-meta.xml
<CustomObject>
    <label>Object B</label>
    <nameField>
        <label>Object B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objects B</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_B__c/fields/Object_A__c.field-meta.xml
<CustomField>
    <fullName>Object_A__c</fullName>
    <label>Object A</label>
    <referenceTo>Object_A__c</referenceTo>
    <relationshipLabel>Objects B</relationshipLabel>
    <relationshipName>Objects_B</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Object_C__c/Object_C__c.object-meta.xml
<CustomObject>
    <label>Object C</label>
    <nameField>
        <label>Object C Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objects C</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_C__c/fields/Object_B__c.field-meta.xml
<CustomField>
    <fullName>Object_B__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Object B</label>
    <referenceTo>Object_B__c</referenceTo>
    <relationshipLabel>Objects C</relationshipLabel>
    <relationshipName>Objects_C</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RelatedRecordsController.cls
public with sharing class RelatedRecordsController {
    public RelatedRecordsController() {
        //
    }

    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getRelatedRecords(Id recordId, Integer pageNumber, Integer pageSize, Integer lastRecord1, Integer lastRecord2) {
        Integer lastTableRecord = pageNumber * pageSize;
        Integer newLastRecord1;
        Integer newLastRecord2;

        if (pageNumber == 1) {
            newLastRecord1 = pageSize;
            newLastRecord2 = 0;
        } 
        else if (lastRecord1 > lastTableRecord) {
            newLastRecord1 = lastTableRecord;
            newLastRecord2 = 0;
        } 
        else {
            newLastRecord1 = lastRecord1;
            newLastRecord2 = (lastTableRecord - lastRecord1);
        }

        List<SObject> recordList = new List<SObject>();
        if (newLastRecord2 == 0) {
            List<SObject> objectBRecs = [SELECT Id, Name FROM Object_B__c WHERE Object_A__c = :recordId LIMIT :pageSize OFFSET :(newLastRecord1 - pageSize)];
            recordList.addAll(objectBRecs);
            
            if (recordList.size() < pageSize) {
                newLastRecord2 = pageSize - recordList.size();
                newLastRecord1 -= pageSize - recordList.size();
            }
        }

        if (newLastRecord2 != 0) {
            List<SObject> objectCRecs = [SELECT Id, Name FROM Object_C__c WHERE Object_B__c IN (SELECT Id FROM Object_B__c WHERE Object_A__c = :recordId) LIMIT :(pageSize - recordList.size()) OFFSET :(newLastRecord2 - pageSize + recordList.size())];
            recordList.addAll(objectCRecs);
            if (recordList.size() < pageSize) {
                newLastRecord2 -= pageSize - recordList.size();
            }
        }

        Map<String, Object> result = new Map<String, Object>();
        result.put('records', recordList);
        result.put('totalRecords', recordList.size());
        result.put('lastRecord1', newLastRecord1);
        result.put('lastRecord2', newLastRecord2);

        return result;
    }
}