force-app/main/default/objects/Object_A__c/Object_A__c.object-meta.xml
<CustomObject>
    <label>Object A</label>
    <nameField>
        <label>Object A Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objects A</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_B__c/Object_B__c.object-meta.xml
<CustomObject>
    <label>Object B</label>
    <nameField>
        <label>Object B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objects B</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_B__c/fields/Object_A__c.field-meta.xml
<CustomField>
    <fullName>Object_A__c</fullName>
    <label>Object A</label>
    <referenceTo>Object_A__c</referenceTo>
    <relationshipLabel>Objects B</relationshipLabel>
    <relationshipName>Objects_B</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Object_C__c/Object_C__c.object-meta.xml
<CustomObject>
    <label>Object C</label>
    <nameField>
        <label>Object C Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objects C</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_C__c/fields/Object_B__c.field-meta.xml
<CustomField>
    <fullName>Object_B__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Object B</label>
    <referenceTo>Object_B__c</referenceTo>
    <relationshipLabel>Objects C</relationshipLabel>
    <relationshipName>Objects_C</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_RelatedRecordsController.cls
@isTest
public with sharing class Test_RelatedRecordsController {
    public Test_RelatedRecordsController() {
        //
    }

    @TestSetup
    public static void makeData(){
        Object_A__c objectA = new Object_A__c(Name = 'Object A');
        insert objectA;

        Object_B__c objectB = new Object_B__c(Name = 'Object B', Object_A__c = objectA.Id);
        insert objectB;

        Object_C__c objectC = new Object_C__c(Name = 'Object C', Object_B__c = objectB.Id);
        insert objectC;
    }

    @isTest
    public static void testCase(){
        
        Test.startTest();
        
        Object_A__c objectA = [SELECT Id FROM Object_A__c LIMIT 1];
        Map<String,Object> results = RelatedRecordsController.getRelatedRecords(objectA.Id, 1, 10, 0, 0);

        Test.stopTest();

        System.assertEquals(2, results.get('totalRecords'), 'Should be 2');
        System.assertEquals(1, results.get('lastRecord1'), 'Should be 1');
        System.assertEquals(1, results.get('lastRecord2'), 'Should be 1');  
    }
}